# Generated by Django 5.1 on 2026-04-14 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('scenario_description', models.TextField(verbose_name='Описание сценария')),
                ('points_reward', models.IntegerField(default=20, verbose_name='Баллы за выполнение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Задание тренажёра',
                'verbose_name_plural': 'Задания тренажёра',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('build_version', models.CharField(max_length=100, verbose_name='Версия билда')),
                ('expected_result', models.TextField(verbose_name='Ожидаемый результат')),
                ('actual_result', models.TextField(verbose_name='Фактический результат')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принято'), ('revision', 'Требует доработки')], default='pending', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='trainer.trainertask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('accepted', 'Принято'), ('revision', 'Требует доработки')], max_length=20, verbose_name='Результат')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='trainer.trainersubmission', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'Проверки',
            },
        ),
    ]
