# Generated by Django 5.1 on 2026-04-14 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('target_role', models.CharField(blank=True, choices=[('employee', 'Новый сотрудник'), ('mentor', 'Наставник'), ('hr', 'Кадровая служба'), ('admin', 'Администратор'), ('', 'Любая роль')], max_length=20, verbose_name='Целевая роль')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('project', models.CharField(blank=True, max_length=100, verbose_name='Проект')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон маршрута',
                'verbose_name_plural': 'Шаблоны маршрутов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdaptationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptation.adaptationtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Маршрут адаптации',
                'verbose_name_plural': 'Маршруты адаптации',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='adaptation.adaptationtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='knowledge.article', verbose_name='Статья базы знаний')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='adaptation.stage', verbose_name='Этап')),
                ('trainer_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptation_tasks', to='trainer.trainertask', verbose_name='Задание тренажёра')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='adaptation.adaptationroute', verbose_name='Маршрут')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='adaptation.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Прогресс задания',
                'verbose_name_plural': 'Прогресс заданий',
                'unique_together': {('route', 'task')},
            },
        ),
    ]
